name: 'Require User Approval'
description: 'Automatically requires reviewers for pull request'
branding:
  icon: 'at-sign'
  color: 'green'
inputs:
  token:
    required: true
  config:
    required: false
    default: '.github/require_reviewers.yml'
runs:
  using: 'node16'
  main: 'dist/index.js'
